# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: seanmcgu@andrew.cmu.edu
author_name: Sean McGuire
create_example_module: false
custom_install: custom
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: false
mypy_type_checking: basic
package_name: lsdb_custom_graphs
project_description: ''
project_license: MIT
project_name: lsdb-custom-graphs
project_organization: smcguire-cmu
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
